/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const RegisterLazyImport = createFileRoute('/register')()
const IndexLazyImport = createFileRoute('/')()
const BookIdCurrPageLazyImport = createFileRoute('/$bookId/$currPage')()

// Create/Update Routes

const RegisterLazyRoute = RegisterLazyImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const BookIdCurrPageLazyRoute = BookIdCurrPageLazyImport.update({
  path: '/$bookId/$currPage',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/$bookId.$currPage.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/$bookId/$currPage': {
      id: '/$bookId/$currPage'
      path: '/$bookId/$currPage'
      fullPath: '/$bookId/$currPage'
      preLoaderRoute: typeof BookIdCurrPageLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  RegisterLazyRoute,
  BookIdCurrPageLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/register",
        "/$bookId/$currPage"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/register": {
      "filePath": "register.lazy.tsx"
    },
    "/$bookId/$currPage": {
      "filePath": "$bookId.$currPage.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
